### 
GET http://localhost:3000/products

###
GET http://localhost:3000/products/1
###
GET http://localhost:3000/products/2

###
POST http://localhost:3000/products
Content-Type: application/json

{
    "id": "2",
    "name": "Jo",
    "price": "20",
    "quantity": "1"
}