### 
GET http://localhost:3000/products?name=/^winn/i

###
GET http://localhost:3000/products/308fe7e7-fe00-4aa2-932b-4fe676317cfe

###
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Jay",
    "price": "20",
    "quantity": ""
}

###
PUT http://localhost:3000/products/2026-05-26T04:43:39.000Z
Content-Type: application/json

{
    "name": "Palm",
    "price": "80",
    "quantity": ""
}

###
DELETE http://localhost:3000/products/2026-05-26T04:43:39.000
